import './button.sass'
import './_submit/button_submit.sass'
import './_transparent/button_transparent.sass'
import './_big/button_big.sass'
import './__text/button__text.sass'
import './_minimal/button_minimal.sass'