import * as $ from 'jquery'
import './fonts/fonts.css'
import './styles/style.sass'
import './components/button/button.js'
import './components/toggle/toggle.js'
import './components/textField/textField.js'
//import './components/dropdown/dropdown.js'
import './components/slider/slider.js'
import './components/filterDateDropdown/filterDateDropdown.js'